### ISSUE TITLE
White Screen - Renderbox did not set its size

### ISSUE THREAD

**Issue by fly-qp** [ufrshubham/dino_run#1]
RenderBox did not set its size during layout.

Because this RenderBox has sizedByParent set to true, it must set its size in performResize().
It appears that this did not happen; layout completed, but the size property is still null.
The RenderBox in question is: GameRenderBox#7a1b6 NEEDS-LAYOUT NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=827.8, h=411.4)
  size: MISSING
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2175:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2300:6)
#2      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1782:9)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:8)
#4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
...
The following RenderObject was being processed when the exception was fired: GameRenderBox#7a1b6 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=827.8, h=411.4)
...  size: MISSING
RenderObject: GameRenderBox#7a1b6 NEEDS-LAYOUT NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=827.8, h=411.4)
  size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: GameRenderBox#7a1b6 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

**Comment by ufrshubham** [comment]
This is just some log. Can you provide some steps for this? What were you doing when this occurred?

**Comment by fly-qp** [comment]
Home Screen works fine. When I hit play whit screen and these errors occurred. Morover on the settings page theres a layout issue.

**Comment by ufrshubham** [comment]
Can you try re-building the project with flame version set to exactly 0.28.0 in pubspec.

You'll just have to change:

`flame: ^0.28.0`

to

`flame: 0.28.0`

**Comment by fly-qp** [comment]
Still the same error.

**Comment by ufrshubham** [comment]
I think the issue might be somewhere in Flame's code. But 0.28.0 is anyways too old and is not recommended. Unfortunately, upgrading this project to latest Flame version isn't trivial. But I've already started rewriting the whole game with latest version of Flame. I'll update the repository as soon as it completes.

**Comment by ufrshubham** [comment]
Migrated the whole project to null-safety and latest packages. This issue is now fixed on `rewrite` branch.
