### ISSUE TITLE
pub get failed (66; , errno = 1314))

### ISSUE THREAD

**Issue by panjunqiao** [ufrshubham/dino_run#2]
Running "flutter pub get" in dino_run...                        
Cannot create link, path = 'G:\AndroidStudioProjects\flutter\.pub-cache\_temp\dir76fa0be4\ios\Classes\AudioplayersPlugin.h' (OS Error: 客户端没有所需的特权。
, errno = 1314)
pub get failed (66; , errno = 1314))
Process finished with exit code 66

**Comment by ufrshubham** [comment]
> Running "flutter pub get" in dino_run... Cannot create link, path = 'G:\AndroidStudioProjects\flutter.pub-cache_temp\dir76fa0be4\ios\Classes\AudioplayersPlugin.h' (OS Error: 客户端没有所需的特权。 , errno = 1314) pub get failed (66; , errno = 1314)) Process finished with exit code 66

I'll need some more information to investigate this.
- Does this happen if you just clone and run this project? Or have you made your own modifications?
- What platform are you building for?
- What are the version of packages you are using? Specially audioplayers.

**Comment by panjunqiao** [comment]
yes,I am clone and run this project

Flutter 2.5.3
Dart 2.14.4
Android Studio 11.0.10

but I just found a solution.
1.Run CMD as Administrator.
2.flutter pub get

Thank you very much
